# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MethClone_one_sample <- function(bamFile1, outFile, sample, d, freq) {
    .Call('_epihet_MethClone_one_sample', PACKAGE = 'epihet', bamFile1, outFile, sample, d, freq)
}

MethClone_two_samples <- function(bamFile1, bamFile2, outFile, sample, d, freq, methdiff) {
    .Call('_epihet_MethClone_two_samples', PACKAGE = 'epihet', bamFile1, bamFile2, outFile, sample, d, freq, methdiff)
}

